language: ruby

before_install: gem install bundler && bundle update --bundler

rvm:
  - 2.3.3
  - 2.4.7
  - 2.5.6
  - ruby-head

gemfile:
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.2.gemfile

matrix:
  exclude:
    - rvm: ruby-head
      gemfile: gemfiles/rails5.0.gemfile