language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head

gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile

matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/rails4.0.gemfile

  allow_failures:
    - rvm: ruby-head
