language: ruby

before_install: gem install bundler && bundle update --bundler

rvm:
  - 2.3.3
  - 2.4.7
  - 2.5.6

gemfile:
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.2.gemfile
  - gemfiles/rails6.0.gemfile

matrix:
  exclude:
    - rvm: 2.3.3
      gemfile: gemfiles/rails6.0.gemfile
    - rvm: 2.4.7
      gemfile: gemfiles/rails6.0.gemfile